# Generated by Django 3.0.1 on 2019-12-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20191223_1450'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
